### ISSUE TITLE
Some files seem to be missing

### ISSUE THREAD

**Issue by bo-son** [HanGuo97/AutoSeM#1]
Hello,

I tried to run your code, but some files (including `utils.py`, `data_utils.py`; there might be some more) seem to be missing.

**Comment by HanGuo97** [comment]
Hi, thanks for the feedback! I will look into that.

**Comment by zhemingyang** [comment]
@HanGuo97 till now, some files (including utils.py, data_utils.py; there might be some more) seem to be missing，i would appreciate it if you could help fix it.
